#!/usr/bin/env bash
#
# sync-openapi.sh — Embed docs/openapi.yaml into the api-docs function.
#
# The Edge Function can't read a sibling .yaml at runtime: Supabase's edge
# runtime compiles each function into a scratch dir and only copies the
# module graph (JS/TS imports), not static assets. So we bake the spec into
# a TS module instead — `openapi.ts` exports the document as a string, which
# makes it part of the module graph and available both locally and once
# deployed.
#
# The source of truth is docs/openapi.yaml. Run this after editing it, and
# again before `supabase functions deploy api-docs`.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
SRC="$ROOT/docs/openapi.yaml"
DEST="$ROOT/supabase/functions/api-docs/openapi.ts"

if [[ ! -f "$SRC" ]]; then
  echo "error: $SRC not found" >&2
  exit 1
fi

# JSON.stringify produces a valid JS string literal with correct escaping for
# any content (backticks, ${…}, quotes, newlines), so the generated module is
# safe regardless of what the YAML contains.
deno eval '
const yaml = await Deno.readTextFile(Deno.args[0]);
const banner =
  "// AUTO-GENERATED by scripts/sync-openapi.sh from docs/openapi.yaml.\n" +
  "// Do not edit by hand — edit docs/openapi.yaml and re-run the script.\n\n";
const body = "export const OPENAPI_YAML = " + JSON.stringify(yaml) + ";\n";
await Deno.writeTextFile(Deno.args[1], banner + body);
' "$SRC" "$DEST"

echo "synced: $SRC → $DEST"
